# Generated by Django 5.2.4 on 2025-08-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationlog',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
