# Generated by Django 5.2.4 on 2025-08-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_rename_timestamp_notificationlog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_channels',
        ),
    ]
