# Generated by Django 5.2.4 on 2025-08-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
